import type { CodeListRegistry } from './types';

/**
 * CODELISTEN – hier werden Codes erklärt.
 *
 * Aufbau: Schlüssel = Nummer des Datenelements (z. B. "3035" für NAD-Beteiligte).
 * Neuen Code ergänzen: einfach eine Zeile in `codes` hinzufügen, z. B.
 *     XY: { label: 'Deutsche Bezeichnung', en: 'English name' },
 * Versionsunterschiede: `since: 'D.01B'` bzw. `until: 'D.07A'` angeben.
 * Der Parser selbst kennt keine Bedeutungen – er fragt nur hier nach.
 *
 * Bewusst nur ein Grundbestand für Lieferavise. Fehlende Codes zeigt die App
 * als „unbekannter Code“ an – es wird nie geraten.
 */
export const CODE_LISTS: CodeListRegistry = {
  // ─── Service-Segmente (UNB/UNG/UNH) ────────────────────────────────────
  '0001': {
    id: '0001',
    name: 'Syntaxkennung (Zeichensatz)',
    en: 'Syntax identifier',
    codes: {
      UNOA: { label: 'Zeichensatz A (nur Großbuchstaben, Ziffern, wenige Sonderzeichen)' },
      UNOB: { label: 'Zeichensatz B (Groß- und Kleinbuchstaben)' },
      UNOC: { label: 'Zeichensatz C (ISO 8859-1, westeuropäisch inkl. Umlaute)' },
      UNOD: { label: 'Zeichensatz D (ISO 8859-2, mitteleuropäisch)' },
      UNOE: { label: 'Zeichensatz E (ISO 8859-5, kyrillisch)' },
      UNOF: { label: 'Zeichensatz F (ISO 8859-7, griechisch)' },
      UNOW: { label: 'Zeichensatz W (UTF-8)' },
      UNOY: { label: 'Zeichensatz Y (ISO 10646, Unicode)' },
    },
  },
  '0007': {
    id: '0007',
    name: 'Qualifier der Partnerkennung',
    en: 'Identification code qualifier',
    codes: {
      '1': { label: 'DUNS-Nummer', en: 'DUNS (Data Universal Numbering System)' },
      '14': { label: 'GS1-Nummer (GLN, früher EAN)', en: 'GS1' },
      ZZ: { label: 'Gegenseitig vereinbart', en: 'Mutually defined' },
      ZZZ: { label: 'Gegenseitig vereinbart', en: 'Mutually defined' },
    },
  },
  '0035': {
    id: '0035',
    name: 'Testkennzeichen',
    en: 'Test indicator',
    codes: {
      '1': { label: 'Testübertragung', en: 'Interchange is a test' },
    },
  },
  '0065': {
    id: '0065',
    name: 'Nachrichtentyp',
    en: 'Message type',
    codes: {
      DESADV: { label: 'Liefermeldung / Lieferavis', en: 'Despatch advice message' },
      ORDERS: { label: 'Bestellung', en: 'Purchase order message' },
      ORDRSP: { label: 'Bestellbestätigung', en: 'Purchase order response message' },
      DELFOR: { label: 'Lieferabruf', en: 'Delivery schedule message' },
      DELJIT: { label: 'Feinabruf (Just-in-time)', en: 'Delivery just in time message' },
      RECADV: { label: 'Wareneingangsmeldung', en: 'Receiving advice message' },
      INVOIC: { label: 'Rechnung', en: 'Invoice message' },
      IFTMIN: { label: 'Transportauftrag', en: 'Instruction message' },
    },
  },
  '0051': {
    id: '0051',
    name: 'Verantwortliche Organisation',
    en: 'Controlling agency',
    codes: {
      UN: { label: 'UN/CEFACT (Vereinte Nationen)', en: 'UN/CEFACT' },
    },
  },

  // ─── Dokument (BGM) ────────────────────────────────────────────────────
  '1001': {
    id: '1001',
    name: 'Dokumentart',
    en: 'Document name code',
    codes: {
      '270': { label: 'Lieferschein', en: 'Delivery note' },
      '351': { label: 'Liefermeldung / Lieferavis', en: 'Despatch advice' },
    },
  },
  '1225': {
    id: '1225',
    name: 'Nachrichtenfunktion',
    en: 'Message function code',
    codes: {
      '1': { label: 'Stornierung', en: 'Cancellation' },
      '3': { label: 'Löschung', en: 'Deletion' },
      '4': { label: 'Änderung', en: 'Change' },
      '5': { label: 'Ersatz', en: 'Replace' },
      '6': { label: 'Bestätigung', en: 'Confirmation' },
      '7': { label: 'Duplikat', en: 'Duplicate' },
      '9': { label: 'Original', en: 'Original' },
      '31': { label: 'Kopie', en: 'Copy' },
    },
  },

  // ─── Datum/Zeit (DTM) ──────────────────────────────────────────────────
  '2005': {
    id: '2005',
    name: 'Art des Datums',
    en: 'Date or time or period function code qualifier',
    codes: {
      '2': { label: 'Gewünschter Liefertermin', en: 'Delivery date/time, requested' },
      '4': { label: 'Bestelldatum', en: 'Order date/time' },
      '10': { label: 'Gewünschter Versandtermin', en: 'Shipment date/time, requested' },
      '11': { label: 'Versanddatum', en: 'Despatch date and/or time' },
      '17': { label: 'Voraussichtlicher Liefertermin', en: 'Delivery date/time, estimated' },
      '35': { label: 'Tatsächlicher Liefertermin', en: 'Delivery date/time, actual' },
      '36': { label: 'Ablaufdatum', en: 'Expiry date' },
      '50': { label: 'Wareneingangsdatum', en: 'Goods receipt date/time' },
      '63': { label: 'Spätester Liefertermin', en: 'Delivery date/time, latest' },
      '64': { label: 'Frühester Liefertermin', en: 'Delivery date/time, earliest' },
      '69': { label: 'Zugesagter Liefertermin', en: 'Delivery date/time, promised for' },
      '76': { label: 'Geplanter Liefertermin', en: 'Delivery date/time, scheduled for' },
      '94': { label: 'Herstelldatum', en: 'Production/manufacture date' },
      '124': { label: 'Lieferscheindatum', en: 'Despatch note date', description: 'Datum, an dem der Lieferschein ausgestellt wurde. Im Automotive-Bereich (VDA) oft statt DTM 137 verwendet.' },
      '132': { label: 'Voraussichtliche Ankunft', en: 'Arrival date/time, estimated' },
      '133': { label: 'Voraussichtliche Abfahrt', en: 'Departure date/time, estimated' },
      '137': { label: 'Dokumentdatum', en: 'Document/message date/time' },
      '171': { label: 'Referenzdatum', en: 'Reference date/time' },
      '178': { label: 'Tatsächliche Ankunft', en: 'Arrival date/time, actual' },
      '186': { label: 'Tatsächliche Abfahrt', en: 'Departure date/time, actual' },
      '200': { label: 'Abholdatum', en: 'Pick-up/collection date/time of cargo' },
      '361': { label: 'Mindesthaltbarkeitsdatum', en: 'Best before date' },
    },
  },
  '2379': {
    id: '2379',
    name: 'Datumsformat',
    en: 'Date or time or period format code',
    codes: {
      '2': { label: 'TTMMJJ' },
      '101': { label: 'JJMMTT' },
      '102': { label: 'JJJJMMTT' },
      '201': { label: 'JJMMTTHHMM' },
      '203': { label: 'JJJJMMTTHHMM' },
      '204': { label: 'JJJJMMTTHHMMSS' },
      '205': { label: 'JJJJMMTTHHMM mit Zeitzone (±HHMM)' },
      '401': { label: 'HHMM (Uhrzeit)' },
      '602': { label: 'JJJJ (Jahr)' },
      '610': { label: 'JJJJMM (Monat)' },
      '616': { label: 'JJJJWW (Kalenderwoche)' },
      '718': { label: 'JJJJMMTT-JJJJMMTT (Zeitraum)' },
      '719': { label: 'JJJJMMTTHHMM-JJJJMMTTHHMM (Zeitraum mit Uhrzeit)' },
    },
  },

  // ─── Referenzen (RFF) ──────────────────────────────────────────────────
  '1153': {
    id: '1153',
    name: 'Art der Referenz',
    en: 'Reference code qualifier',
    codes: {
      AAJ: { label: 'Lieferauftragsnummer', en: 'Delivery order number' },
      AAK: { label: 'Liefermeldungsnummer', en: 'Despatch advice number' },
      AAN: { label: 'Lieferabrufnummer', en: 'Delivery schedule number' },
      AAS: { label: 'Transportdokumentnummer', en: 'Transport document number' },
      AAU: { label: 'Lieferscheinnummer (Versandschein)', en: 'Despatch note number' },
      BM: { label: 'Konnossementsnummer', en: 'Bill of lading number' },
      BT: { label: 'Chargennummer', en: 'Batch number/lot number' },
      CR: { label: 'Kundenreferenz', en: 'Customer reference number' },
      CT: { label: 'Vertragsnummer', en: 'Contract number' },
      CU: { label: 'Referenz des Versenders', en: "Consignor's reference number" },
      DQ: { label: 'Lieferscheinnummer', en: 'Delivery note number' },
      FC: { label: 'Steuernummer', en: 'Fiscal number' },
      IV: { label: 'Rechnungsnummer', en: 'Invoice number' },
      LI: { label: 'Positionsnummer', en: 'Line item reference number' },
      ON: { label: 'Bestellnummer (Käufer)', en: 'Order number (buyer)' },
      PK: { label: 'Packlistennummer', en: 'Packing list number' },
      VA: { label: 'Umsatzsteuer-Identifikationsnummer', en: 'VAT registration number' },
      VN: { label: 'Auftragsnummer (Lieferant)', en: 'Order number (supplier)' },
    },
  },

  // ─── Beteiligte (NAD, CTA, COM) ────────────────────────────────────────
  '3035': {
    id: '3035',
    name: 'Rolle des Beteiligten',
    en: 'Party function code qualifier',
    codes: {
      BY: { label: 'Käufer', en: 'Buyer' },
      CA: { label: 'Frachtführer / Spediteur', en: 'Carrier' },
      CN: { label: 'Warenempfänger', en: 'Consignee' },
      CZ: { label: 'Versender', en: 'Consignor' },
      DP: { label: 'Lieferanschrift', en: 'Delivery party' },
      FW: { label: 'Spediteur (Speditionsbetrieb)', en: 'Freight forwarder' },
      IV: { label: 'Rechnungsempfänger', en: 'Invoicee' },
      MF: { label: 'Hersteller', en: 'Manufacturer of goods' },
      MI: { label: 'Aussteller des Lieferabrufs', en: 'Planning schedule/material release issuer' },
      OB: { label: 'Besteller', en: 'Ordered by' },
      SE: { label: 'Verkäufer', en: 'Seller' },
      SF: { label: 'Versandort (Abholadresse)', en: 'Ship from' },
      ST: { label: 'Lieferanschrift (Empfänger)', en: 'Ship to' },
      SU: { label: 'Lieferant', en: 'Supplier' },
      UC: { label: 'Endempfänger', en: 'Ultimate consignee' },
      WH: { label: 'Lagerhalter', en: 'Warehouse keeper' },
    },
  },
  '3055': {
    id: '3055',
    name: 'Verantwortliche Stelle der Codeliste',
    en: 'Code list responsible agency code',
    codes: {
      '5': { label: 'ISO' },
      '6': { label: 'UN/ECE' },
      '9': { label: 'GS1 (früher EAN International)' },
      '16': { label: 'Dun & Bradstreet (DUNS)' },
      '91': { label: 'Vom Lieferanten vergeben', en: 'Assigned by seller or seller\'s agent' },
      '92': { label: 'Vom Käufer vergeben', en: 'Assigned by buyer or buyer\'s agent' },
    },
  },
  '3139': {
    id: '3139',
    name: 'Funktion des Ansprechpartners',
    en: 'Contact function code',
    codes: {
      IC: { label: 'Ansprechpartner für Informationen', en: 'Information contact' },
      OC: { label: 'Ansprechpartner für Bestellungen', en: 'Order contact' },
      PD: { label: 'Einkauf', en: 'Purchasing contact' },
    },
  },
  '3155': {
    id: '3155',
    name: 'Kommunikationsweg',
    en: 'Communication means type code',
    codes: {
      EM: { label: 'E-Mail', en: 'Electronic mail' },
      FX: { label: 'Telefax', en: 'Telefax' },
      TE: { label: 'Telefon', en: 'Telephone' },
    },
  },
  '3207': {
    id: '3207',
    name: 'Land (ISO 3166)',
    en: 'Country identifier',
    codes: {
      AT: { label: 'Österreich' },
      BE: { label: 'Belgien' },
      CH: { label: 'Schweiz' },
      CN: { label: 'China' },
      CZ: { label: 'Tschechien' },
      DE: { label: 'Deutschland' },
      DK: { label: 'Dänemark' },
      ES: { label: 'Spanien' },
      FR: { label: 'Frankreich' },
      GB: { label: 'Vereinigtes Königreich' },
      HU: { label: 'Ungarn' },
      IT: { label: 'Italien' },
      JP: { label: 'Japan' },
      LU: { label: 'Luxemburg' },
      MX: { label: 'Mexiko' },
      NL: { label: 'Niederlande' },
      PL: { label: 'Polen' },
      PT: { label: 'Portugal' },
      RO: { label: 'Rumänien' },
      SE: { label: 'Schweden' },
      SI: { label: 'Slowenien' },
      SK: { label: 'Slowakei' },
      TR: { label: 'Türkei' },
      US: { label: 'Vereinigte Staaten' },
    },
  },

  // ─── Orte (LOC) ────────────────────────────────────────────────────────
  '3227': {
    id: '3227',
    name: 'Art des Ortes',
    en: 'Location function code qualifier',
    codes: {
      '5': { label: 'Abgangsort', en: 'Place of departure' },
      '7': { label: 'Lieferort', en: 'Place of delivery' },
      '8': { label: 'Bestimmungsort', en: 'Place of destination' },
      '9': { label: 'Ladeort', en: 'Place/port of loading' },
      '11': { label: 'Entladeort / Abladestelle', en: 'Place/port of discharge' },
      '18': { label: 'Lager', en: 'Warehouse' },
      '159': { label: 'Zusätzlicher interner Bestimmungsort', en: 'Additional internal destination' },
    },
  },

  // ─── Transport (TDT, TOD, EQD) ─────────────────────────────────────────
  '8051': {
    id: '8051',
    name: 'Transportabschnitt',
    en: 'Transport stage code qualifier',
    codes: {
      '10': { label: 'Vorlauf', en: 'Pre-carriage transport' },
      '20': { label: 'Hauptlauf', en: 'Main-carriage transport' },
      '30': { label: 'Nachlauf', en: 'On-carriage transport' },
    },
  },
  '8067': {
    id: '8067',
    name: 'Verkehrszweig',
    en: 'Transport mode name code',
    codes: {
      '0': { label: 'Nicht angegeben', en: 'Transport mode not specified' },
      '1': { label: 'Seeverkehr', en: 'Maritime transport' },
      '2': { label: 'Eisenbahn', en: 'Rail transport' },
      '3': { label: 'Straße (Lkw)', en: 'Road transport' },
      '4': { label: 'Luftfracht', en: 'Air transport' },
      '5': { label: 'Post', en: 'Mail' },
      '6': { label: 'Multimodal', en: 'Multimodal transport' },
      '7': { label: 'Feste Transporteinrichtung (z. B. Pipeline)', en: 'Fixed transport installation' },
      '8': { label: 'Binnenschifffahrt', en: 'Inland water transport' },
      '9': { label: 'Verkehrszweig nicht zutreffend', en: 'Transport mode not applicable' },
    },
  },
  '4053': {
    id: '4053',
    name: 'Lieferbedingung (Incoterms)',
    en: 'Delivery or transport terms description code',
    codes: {
      EXW: { label: 'Ab Werk', en: 'Ex Works' },
      FCA: { label: 'Frei Frachtführer', en: 'Free Carrier' },
      CPT: { label: 'Frachtfrei', en: 'Carriage Paid To' },
      CIP: { label: 'Frachtfrei versichert', en: 'Carriage and Insurance Paid To' },
      DAP: { label: 'Geliefert benannter Ort', en: 'Delivered At Place' },
      DPU: { label: 'Geliefert benannter Ort entladen', en: 'Delivered at Place Unloaded' },
      DDP: { label: 'Geliefert verzollt', en: 'Delivered Duty Paid' },
      FAS: { label: 'Frei Längsseite Schiff', en: 'Free Alongside Ship' },
      FOB: { label: 'Frei an Bord', en: 'Free On Board' },
      CFR: { label: 'Kosten und Fracht', en: 'Cost and Freight' },
      CIF: { label: 'Kosten, Versicherung und Fracht', en: 'Cost, Insurance and Freight' },
    },
  },
  '8053': {
    id: '8053',
    name: 'Art des Transportequipments',
    en: 'Equipment type code qualifier',
    codes: {
      CN: { label: 'Container', en: 'Container' },
      TE: { label: 'Anhänger / Trailer', en: 'Trailer' },
    },
  },

  // ─── Maße und Mengen (MEA, QTY, CNT) ───────────────────────────────────
  '6311': {
    id: '6311',
    name: 'Zweck der Messung',
    en: 'Measurement purpose code qualifier',
    codes: {
      AAE: { label: 'Messung', en: 'Measurement' },
      AAX: { label: 'Sendungsmessung', en: 'Consignment measurement' },
      CT: { label: 'Zählung', en: 'Counts' },
      PD: { label: 'Physische Abmessungen', en: 'Physical dimensions (product ordered)' },
    },
  },
  '6313': {
    id: '6313',
    name: 'Gemessene Eigenschaft',
    en: 'Measured attribute code',
    codes: {
      AAA: { label: 'Nettogewicht je Einheit', en: 'Unit net weight' },
      AAB: { label: 'Bruttogewicht je Einheit', en: 'Unit gross weight' },
      AAC: { label: 'Gesamtnettogewicht', en: 'Total net weight' },
      AAD: { label: 'Gesamtbruttogewicht', en: 'Total gross weight' },
      AAW: { label: 'Bruttovolumen', en: 'Gross volume' },
      HT: { label: 'Höhe', en: 'Height dimension' },
      LN: { label: 'Länge', en: 'Length dimension' },
      WD: { label: 'Breite', en: 'Width dimension' },
    },
  },
  '6063': {
    id: '6063',
    name: 'Art der Menge',
    en: 'Quantity type code qualifier',
    codes: {
      '1': { label: 'Einzelmenge', en: 'Discrete quantity' },
      '3': { label: 'Kumulierte Menge', en: 'Cumulative quantity' },
      '12': { label: 'Liefermenge', en: 'Despatch quantity' },
      '21': { label: 'Bestellmenge', en: 'Ordered quantity' },
      '46': { label: 'Gelieferte Menge', en: 'Delivered quantity' },
      '48': { label: 'Empfangene Menge', en: 'Received quantity' },
      '52': { label: 'Menge je Packstück', en: 'Quantity per pack' },
      '59': { label: 'Anzahl Verbrauchereinheiten je Handelseinheit', en: 'Number of consumer units in the traded unit' },
      '83': { label: 'Rückstandsmenge', en: 'Backorder quantity' },
      '113': { label: 'Zu liefernde Menge', en: 'Quantity to be delivered' },
      '192': { label: 'Kostenlose Menge', en: 'Free goods quantity' },
    },
  },
  '6411': {
    id: '6411',
    name: 'Maßeinheit',
    en: 'Measurement unit code',
    codes: {
      C62: { label: 'Stück (Einheit „eins“)', en: 'one' },
      CMT: { label: 'Zentimeter', en: 'centimetre' },
      DMT: { label: 'Dezimeter', en: 'decimetre' },
      EA: { label: 'Stück', en: 'each' },
      GRM: { label: 'Gramm', en: 'gram' },
      H87: { label: 'Stück', en: 'piece' },
      KGM: { label: 'Kilogramm', en: 'kilogram' },
      LTR: { label: 'Liter', en: 'litre' },
      MMT: { label: 'Millimeter', en: 'millimetre' },
      MTK: { label: 'Quadratmeter', en: 'square metre' },
      MTQ: { label: 'Kubikmeter', en: 'cubic metre' },
      MTR: { label: 'Meter', en: 'metre' },
      PCE: { label: 'Stück', en: 'piece' },
      PR: { label: 'Paar', en: 'pair' },
      SET: { label: 'Satz', en: 'set' },
      TNE: { label: 'Tonne', en: 'tonne (metric ton)' },
    },
  },
  '6069': {
    id: '6069',
    name: 'Art der Kontrollsumme',
    en: 'Control total type code qualifier',
    codes: {
      '1': { label: 'Summe aller Mengen in den Positionen', en: 'Algebraic total of the quantity values in line items in a message' },
      '2': { label: 'Anzahl der Positionen', en: 'Number of line items in message' },
    },
  },

  // ─── Verpackung (CPS, PAC, PCI, GIN) ───────────────────────────────────
  '7075': {
    id: '7075',
    name: 'Verpackungsebene',
    en: 'Packaging level code',
    codes: {
      '1': { label: 'Innere Verpackung', en: 'Inner' },
      '2': { label: 'Zwischenverpackung', en: 'Intermediate' },
      '3': { label: 'Äußere Verpackung', en: 'Outer' },
      '4': { label: 'Keine Verpackungshierarchie', en: 'No packaging hierarchy' },
    },
  },
  '7065': {
    id: '7065',
    name: 'Packmittelart',
    en: 'Package type description code',
    description: 'Codes nach UN/ECE-Empfehlung 21. Kunden- oder lieferantenspezifische Packmittelnummern (z. B. aus der VDA-Welt) stehen nicht hier.',
    codes: {
      BG: { label: 'Sack / Beutel', en: 'Bag' },
      BX: { label: 'Kiste / Box', en: 'Box' },
      CR: { label: 'Lattenkiste', en: 'Crate' },
      CS: { label: 'Kiste', en: 'Case' },
      CT: { label: 'Karton', en: 'Carton' },
      DR: { label: 'Fass / Trommel', en: 'Drum' },
      PK: { label: 'Packung', en: 'Package' },
      PU: { label: 'Tray', en: 'Tray' },
      PX: { label: 'Palette', en: 'Pallet' },
      RO: { label: 'Rolle', en: 'Roll' },
      SW: { label: 'Schrumpfverpackt', en: 'Shrinkwrapped' },
    },
  },
  '4233': {
    id: '4233',
    name: 'Markierungsanweisung',
    en: 'Marking instructions code',
    codes: {
      '33E': { label: 'Mit SSCC gekennzeichnet (GS1-128-Etikett)', en: 'Marked with serial shipping container code' },
    },
  },
  '7405': {
    id: '7405',
    name: 'Art der Identifikationsnummer',
    en: 'Object identification code qualifier',
    codes: {
      BJ: { label: 'SSCC (Nummer der Versandeinheit)', en: 'Serial shipping container code' },
      BN: { label: 'Seriennummer', en: 'Serial number' },
      BX: { label: 'Chargennummer', en: 'Batch number' },
      ML: { label: 'Packstück-Etikettennummer', en: 'Marking/label number' },
    },
  },

  // ─── Positionen (LIN, PIA, IMD) ────────────────────────────────────────
  '1229': {
    id: '1229',
    name: 'Änderungskennzeichen der Position',
    en: 'Action request/notification description code',
    codes: {
      '1': { label: 'Hinzugefügt', en: 'Added' },
      '2': { label: 'Gelöscht', en: 'Deleted' },
      '3': { label: 'Geändert', en: 'Changed' },
    },
  },
  '7143': {
    id: '7143',
    name: 'Art der Artikelnummer',
    en: 'Item type identification code',
    codes: {
      BP: { label: 'Teilenummer des Käufers', en: "Buyer's part number" },
      DR: { label: 'Zeichnungsänderungsstand', en: 'Drawing revision number' },
      EC: { label: 'Änderungsstand (Engineering Change)', en: 'Engineering change level' },
      EN: { label: 'EAN-Nummer', en: 'International Article Numbering Association (EAN)' },
      IN: { label: 'Artikelnummer des Käufers', en: "Buyer's item number" },
      MF: { label: 'Artikelnummer des Herstellers', en: "Manufacturer's (producer's) article number" },
      NB: { label: 'Chargennummer', en: 'Batch number' },
      SA: { label: 'Artikelnummer des Lieferanten', en: "Supplier's article number" },
      SN: { label: 'Seriennummer', en: 'Serial number' },
      SRV: { label: 'GTIN (GS1-Artikelnummer)', en: 'GS1 Global Trade Item Number' },
      UP: { label: 'UPC-Nummer', en: 'UPC (Universal product code)' },
      VP: { label: 'Teilenummer des Lieferanten', en: "Vendor's (seller's) part number" },
    },
  },
  '4347': {
    id: '4347',
    name: 'Funktion der Produktkennung',
    en: 'Product identifier code qualifier',
    codes: {
      '1': { label: 'Zusätzliche Identifikation', en: 'Additional identification' },
      '5': { label: 'Produktidentifikation', en: 'Product identification' },
    },
  },
  '7077': {
    id: '7077',
    name: 'Art der Beschreibung',
    en: 'Description format code',
    codes: {
      A: { label: 'Freitext, lang', en: 'Free-form long description' },
      B: { label: 'Code und Text', en: 'Code and text' },
      C: { label: 'Code', en: 'Code (from industry code list)' },
      E: { label: 'Freitext, kurz', en: 'Free-form short description' },
      F: { label: 'Freitext', en: 'Free-form' },
      S: { label: 'Strukturiert (Codeliste der Branche)', en: 'Structured (industry code list)' },
    },
  },

  // ─── Freitext (FTX) ────────────────────────────────────────────────────
  '4451': {
    id: '4451',
    name: 'Thema des Freitexts',
    en: 'Text subject code qualifier',
    codes: {
      AAI: { label: 'Allgemeine Information', en: 'General information' },
      DEL: { label: 'Lieferhinweis', en: 'Delivery information' },
      PAC: { label: 'Verpackungs-/Markierungshinweis', en: 'Packing/marking information' },
      ZZZ: { label: 'Gegenseitig vereinbart', en: 'Mutually defined' },
    },
  },
};
